version: "3.9"

services:
  backend:
    build: .
    container_name: notesapp-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: notesapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notesapp
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
